In [18]:
#First five rows of the csv file
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.head()

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN

In [24]:
#To print specific columns like restaurant ID,City,State and Country and name of columns in one single cell
import pandas as pd
df = pd.read_csv('restaurants.csv')
display(df[['Restaurant_ID', 'Name', 'City','State','Country']])
print(df.columns)

,Restaurant_ID,Name,City,State,Country
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico
...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico
129,135109,Paniroles,Cuernavaca,Morelos,Mexico

Index(['Restaurant_ID', 'Name', 'City', 'State', 'Country', 'Zip_Code',
       'Latitude', 'Longitude', 'Alcohol_Service', 'Smoking_Allowed', 'Price',
       'Franchise', 'Area', 'Parking'],
      dtype='str')

In [9]:
#Now print the column names
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.columns

Index(['Restaurant_ID', 'Name', 'City', 'State', 'Country', 'Zip_Code',
       'Latitude', 'Longitude', 'Alcohol_Service', 'Smoking_Allowed', 'Price',
       'Franchise', 'Area', 'Parking'],
      dtype='str')

In [10]:
#To print all the rows where State name is Morelos
import pandas as pd
df = pd.read_csv('restaurants.csv')
df[df['State']=='Morelos']

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
27,132766,Mikasa,Cuernavaca,Morelos,Mexico,NaN,18.910178,-99.231544,Wine & Beer,No,Medium,No,Closed,Yes
28,132767,Restaurant Familiar El Chino,Jiutepec,Morelos,Mexico,NaN,18.882087,-99.163027,Wine & Beer,Yes,Medium,No,Open,Yes
29,132768,Mariscos Tia Licha,Cuernavaca,Morelos,Mexico,62320.0,18.925773,-99.232636,NaN,No,Medium,Yes,Closed,NaN
30,132773,El Cotorreo,Cuernavaca,Morelos,Mexico,NaN,18.869993,-99.210319,Wine & Beer,Yes,Low,No,Open,NaN
59,134975,Rincon Del Bife,Cuernavaca,Morelos,Mexico,NaN,18.940828,-99.215426,Full Bar,Smoking Section,High,No,Closed,Valet
60,134976,Log Yin,Cuernavaca,Morelos,Mexico,NaN,18.916654,-99.227110,NaN,No,Low,No,Closed,Yes
61,134983,Restaurant And Bar And Clothesline Carlos N Ch...,Cuernavaca,Morelos,Mexico,62250.0,18.948657,-99.235361,Full Bar,Smoking Section,High,No,Closed,Yes
62,134986,Restaurant Las Mañanitas,Cuernavaca,Morelos,Mexico,NaN,18.928798,-99.239513,Wine & Beer,No,High,No,Closed,Yes
63,134987,Chilis Cuernavaca,Cuernavaca,Morelos,Mexico,62290.0,18.932725,-99.225211,Wine & Beer,No,Medium,No,Closed,NaN
64,134992,Restaurant Teely,Cuernavaca,Morelos,Mexico,NaN,18.936683,-99.247366,Wine & Beer,Smoking Section,High,No,Closed,Yes
65,134996,Sanborns Casa Piedra,Cuernavaca,Morelos,Mexico,NaN,18.923429,-99.216413,Wine & Beer,Bar Only,Medium,Yes,Closed,Yes
66,134999,Kiku Cuernavaca,Cuernavaca,Morelos,Mexico,NaN,18.915421,-99.184871,NaN,No,Medium,No,Closed,NaN
67,135000,Restaurant Los Pinos,Cuernavaca,Morelos,Mexico,62790.0,18.870565,-99.226938,NaN,No,Medium,No,Closed,NaN
68,135001,Vips,Cuernavaca,Morelos,Mexico,62170.0,18.941859,-99.241927,Wine & Beer,No,Medium,Yes,Closed,Yes
69,135011,Los Vikingos,Cuernavaca,Morelos,Mexico,NaN,18.910610,-99.169539,NaN,No,Medium,Yes,Closed,NaN
70,135013,Giovannis,Cuernavaca,Morelos,Mexico,NaN,18.917441,-99.165945,NaN,No,Low,No,Closed,NaN
71,135016,Arrachela Grill,Cuernavaca,Morelos,Mexico,NaN,18.869347,-99.209944,NaN,No,Medium,No,Closed,NaN
72,135018,El Oceano Dorado,Cuernavaca,Morelos,Mexico,NaN,18.859803,-99.222164,Full Bar,Yes,Medium,No,Open,Yes
73,135019,Restaurant Bar Coty Y Pablo,Jiutepec,Morelos,Mexico,NaN,18.875011,-99.159422,NaN,No,Low,No,Closed,NaN
74,135021,Subway,Cuernavaca,Morelos,Mexico,62290.0,18.933537,-99.222497,NaN,No,Low,Yes,Closed,Public
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

In [23]:
#To print specific attributes
import pandas as pd
df = pd.read_csv('restaurants.csv')
print(df.shape) #To print number of rows and columns 
print(df.size) #To print the number of datapoints in the dataset
print(df.ndim) #To show how many dimensions is the table
len(df) #To print the number of rows

(130, 14)
1820
2

130

In [1]:
#Sorting data based on one column(Name)
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.sort_values(by='Name')

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
111,135069,Abondance Restaurante Bar,San Luis Potosi,San Luis Potosi,Mexico,78399.0,22.140129,-100.944872,Wine & Beer,No,Low,No,Closed,Yes
71,135016,Arrachela Grill,Cuernavaca,Morelos,Mexico,NaN,18.869347,-99.209944,NaN,No,Medium,No,Closed,NaN
25,132754,Cabana Huasteca,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.147738,-100.990616,NaN,No,Medium,No,Closed,NaN
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,132870,Tortas Y Hamburguesas El Gordo,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.143078,-100.935479,NaN,No,Low,No,Closed,NaN
39,132856,Unicol's Pizza,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.151378,-100.974634,Wine & Beer,No,Low,No,Closed,NaN
55,132951,Vips,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.154474,-100.985809,NaN,No,Low,No,Closed,Yes
68,135001,Vips,Cuernavaca,Morelos,Mexico,62170.0,18.941859,-99.241927,Wine & Beer,No,Medium,Yes,Closed,Yes
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes

In [2]:
#Print unique city names
import pandas as pd
df = pd.read_csv('restaurants.csv')
df['City'].unique()

<StringArray>
['Ciudad Victoria', 'San Luis Potosi', 'Cuernavaca', 'Jiutepec']
Length: 4, dtype: str

In [3]:
#To print count,mean,standard deviation,minimum,maximum and percentiles all at once
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.describe()

       Restaurant_ID      Zip_Code    Latitude   Longitude
count     130.000000     56.000000  130.000000  130.000000
mean   134012.784615  75790.714286   21.858863 -100.342933
std      1140.644582   6018.162410    1.496830    0.860585
min    132560.000000  62000.000000   18.859803 -101.028600
25%    132831.000000  78000.000000   22.139574 -100.987838
50%    134994.000000  78212.000000   22.149063 -100.956777
75%    135050.750000  78310.000000   22.160125  -99.220458
max    135109.000000  87018.000000   23.760268  -99.126506

In [4]:
#To print rows matching certain conditions
import pandas as pd
df = pd.read_csv('restaurants.csv')
df[(df['State'] == 'Morelos') & (df['City'] == 'Cuernavaca')]

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
27,132766,Mikasa,Cuernavaca,Morelos,Mexico,NaN,18.910178,-99.231544,Wine & Beer,No,Medium,No,Closed,Yes
29,132768,Mariscos Tia Licha,Cuernavaca,Morelos,Mexico,62320.0,18.925773,-99.232636,NaN,No,Medium,Yes,Closed,NaN
30,132773,El Cotorreo,Cuernavaca,Morelos,Mexico,NaN,18.869993,-99.210319,Wine & Beer,Yes,Low,No,Open,NaN
59,134975,Rincon Del Bife,Cuernavaca,Morelos,Mexico,NaN,18.940828,-99.215426,Full Bar,Smoking Section,High,No,Closed,Valet
60,134976,Log Yin,Cuernavaca,Morelos,Mexico,NaN,18.916654,-99.227110,NaN,No,Low,No,Closed,Yes
61,134983,Restaurant And Bar And Clothesline Carlos N Ch...,Cuernavaca,Morelos,Mexico,62250.0,18.948657,-99.235361,Full Bar,Smoking Section,High,No,Closed,Yes
62,134986,Restaurant Las Mañanitas,Cuernavaca,Morelos,Mexico,NaN,18.928798,-99.239513,Wine & Beer,No,High,No,Closed,Yes
63,134987,Chilis Cuernavaca,Cuernavaca,Morelos,Mexico,62290.0,18.932725,-99.225211,Wine & Beer,No,Medium,No,Closed,NaN
64,134992,Restaurant Teely,Cuernavaca,Morelos,Mexico,NaN,18.936683,-99.247366,Wine & Beer,Smoking Section,High,No,Closed,Yes
65,134996,Sanborns Casa Piedra,Cuernavaca,Morelos,Mexico,NaN,18.923429,-99.216413,Wine & Beer,Bar Only,Medium,Yes,Closed,Yes
66,134999,Kiku Cuernavaca,Cuernavaca,Morelos,Mexico,NaN,18.915421,-99.184871,NaN,No,Medium,No,Closed,NaN
67,135000,Restaurant Los Pinos,Cuernavaca,Morelos,Mexico,62790.0,18.870565,-99.226938,NaN,No,Medium,No,Closed,NaN
68,135001,Vips,Cuernavaca,Morelos,Mexico,62170.0,18.941859,-99.241927,Wine & Beer,No,Medium,Yes,Closed,Yes
69,135011,Los Vikingos,Cuernavaca,Morelos,Mexico,NaN,18.910610,-99.169539,NaN,No,Medium,Yes,Closed,NaN
70,135013,Giovannis,Cuernavaca,Morelos,Mexico,NaN,18.917441,-99.165945,NaN,No,Low,No,Closed,NaN
71,135016,Arrachela Grill,Cuernavaca,Morelos,Mexico,NaN,18.869347,-99.209944,NaN,No,Medium,No,Closed,NaN
72,135018,El Oceano Dorado,Cuernavaca,Morelos,Mexico,NaN,18.859803,-99.222164,Full Bar,Yes,Medium,No,Open,Yes
74,135021,Subway,Cuernavaca,Morelos,Mexico,62290.0,18.933537,-99.222497,NaN,No,Low,Yes,Closed,Public
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

In [5]:
#To use group-by funcytion and find the average value based on a particular group for example state
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.groupby('State').mean(numeric_only=True)

                 Restaurant_ID      Zip_Code   Latitude   Longitude
State
Morelos          134515.086957  62301.428571  18.909978  -99.214641
San Luis Potosi  134219.547619  77524.000000  22.149658 -100.976882
Tamaulipas       132755.347826  87018.000000  23.745717  -99.155931

In [6]:
#To print specifc rows and specific columns at once using index
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.iloc[0:3, 0:2]

   Restaurant_ID                Name
0         132560  Puesto de Gorditas
1         132561          Cafe Ambar
2         132564            Church's

In [7]:
#To print specific rows and columns based on names of rows and columns
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.loc[0:4, ['Name', 'State']]

                 Name            State
0  Puesto de Gorditas       Tamaulipas
1          Cafe Ambar       Tamaulipas
2            Church's       Tamaulipas
3        Cafe Chaires  San Luis Potosi
4    McDonalds Centro          Morelos

In [8]:
#To print the Name and City of rows whose values have state as Tamaulipas
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.loc[df['State'] == 'Tamaulipas', ['Name', 'City']]

                                      Name             City
0                       Puesto de Gorditas  Ciudad Victoria
1                               Cafe Ambar  Ciudad Victoria
2                                 Church's  Ciudad Victoria
5                       Gorditas Doña Tota  Ciudad Victoria
6       Tacos De Barbacoa Enfrente Del Tec  Ciudad Victoria
7                   Hamburguesas La Perica  Ciudad Victoria
8                 Pollo Frito Buenos Aires  Ciudad Victoria
9                            Carnitas Mata  Ciudad Victoria
10                   La Perica Hamburguesa  Ciudad Victoria
11                              Palomo Tec  Ciudad Victoria
12   Carnitas Mata  Calle 16 de Septiembre  Ciudad Victoria
13   Carnitas Mata Calle Emilio Portes Gil  Ciudad Victoria
14                               Tacos Abi  Ciudad Victoria
15                      Tacos Correcaminos  Ciudad Victoria
16          Little Pizza Emilio Portes Gil  Ciudad Victoria
17                          Tacos El Guero  Ciudad Victoria
18                      Gorditas Dona Tota  Ciudad Victoria
19                    Tacos De La Estacion  Ciudad Victoria
20                           Tortas Hawaii  Ciudad Victoria
22                      Taqueria El Amigo   Ciudad Victoria
23                          Little Caesars  Ciudad Victoria
24           Carreton De Flautas Y Migadas  Ciudad Victoria
126                                   Vips  Ciudad Victoria

In [9]:
#To rename columns of the csv file
import pandas as pd
df = pd.read_csv('restaurants.csv')
df.rename(columns={'Name': 'Restaurant_Name', 'City': 'Location_City'}, inplace=True)
df.head()

,Restaurant_ID,Restaurant_Name,Location_City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN